### ISSUE TITLE
Verify signature. Is python3 compatible?

### ISSUE THREAD

**Issue by jlmadurga** [kikinteractive/kik-python#14]
First of all: Is this library planned to be python3 compatible?

In verify_signature function in python3 raises:

`TypeError: key: expected bytes or bytearray, but got 'str'`

I think `str` must be removed here:

```return signature == base64.b16encode(hmac.new(str(self.api_key),** body, hashlib.sha1).digest())```

**Comment by mmailhot** [comment]
Should be fixed in 1.0.7.
