### ISSUE TITLE
Cannot import module

### ISSUE THREAD

**Issue by urigoren** [kikinteractive/kik-python#29]
I ran `pip kik install` and the installation was successful.

However, it throws an exception when I try to import it

> > > import kik
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "kik.py", line 3, in <module>
> > >     from kik import KikApi, Configuration
> > > ImportError: cannot import name KikApi

**Comment by kmcgaire** [comment]
@urigoren 
can you run `pip install kik` I think you just have your parameters out of order

**Comment by janbomstrom** [comment]
Hi urigoren,

Try renaming your script. Looks it is now "kik.py" which is not possible because now you are trying to import your own script.
