### ISSUE TITLE
Traceback error 

### ISSUE THREAD

**Issue by Jarmahent** [kikinteractive/kik-python#4]
Doing:
>> from kik import KikApi
>> kik = KikApi(BOT_USERNAME, BOT_API_KEY)
>> config = kik.get_configuration()
>> config.webhook

Errror:

http://puu.sh/o929u/140f3d4b29.png

**Comment by mmailhot** [comment]
@Jarmahent Thanks for the report. Looks like a python3 bytes/str issue, PR incoming to fix.

**Comment by mmailhot** [comment]
This should be fixed by #6 in 1.0.4
