### ISSUE TITLE
Incorrect User-Ids in public groups

### ISSUE THREAD

**Issue by slideup-benni** [kikinteractive/kik-python#46]
Hello,

when i use the bot in a public group the API returns incorrect User-Ids like 
"gglyuuddtf3amvvixcb7jf33qug6wkm5ierg2kn77kdnuwhvndhq" (changed some letters) 
instead of the real user-id

how can i fix this?

I'm sure it worked a few days ago.

**Comment by XenXenOfficial** [comment]
I believe its a new security measure implemented by Kik
