### ISSUE TITLE
Unauthorized response

### ISSUE THREAD

**Issue by jaybaker** [kikinteractive/kik-python#9]
I am trying the example from https://kik.readthedocs.org/en/latest/user.html#configuration
I literally copied the code into the python interpreter.

I get "Unauthorized" for all requests though.
I tried setting configuration too. 

Is it possible that Kik changed something? I assume others are not having the auth issue.

**Comment by mmailhot** [comment]
@jaybaker Can you double check that the correct bot username and api key are substituted in? If so, if you could send me your bot's username, either here or by emailing bots@kik.com I can look into what's happening.

**Comment by Lazarus118** [comment]
I am also having some issues with **configuration**. Does the "/incoming" route needs to be on a secured http site?

`
>>> config = Configuration(webhook='getsyouwhat.pythonanywhere.com/incoming')
>>> kik.set_configuration(config)

/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/kik/api.py", line 237, in set_configuration
    raise KikError(response.text)
kik.error.KikError: {"message":"Invalid config","error":"BadRequest"}
`

**Comment by mmailhot** [comment]
@Lazarus118 You need to include the protocol (`http://` or `https://`) on the URL for your webhook

**Comment by Lazarus118** [comment]
I did.. Does the same thing.

**Comment by cgurnik** [comment]
@jaybaker @Lazarus118 Thanks for the bug reports! This issue should be resolved in v1.0.6.
